server:
  port: 8083
  servlet:
    context-path: /springboot_all
spring:
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: admin